package com.veersa.emailer.dto;

import  lombok.*;

@Data
public class EmailRequestDto {

    private String to;
    private String subject;
    private String body;


    // getter and setter methods are generated by Lombok's @Data annotation
}
